//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ararat_Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string content_Comment { get; set; }
        public string content_image_URL { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> comment_For_id { get; set; }
        public Nullable<int> Type_For { get; set; }
    }
}
