//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ararat_Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public string contentPost { get; set; }
        public string imageURL { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public Nullable<int> user_Id { get; set; }
    }
}
